ALTER TABLE `Contract`
  MODIFY COLUMN `status` ENUM('DRAFT', 'APPROVING', 'APPROVED', 'REJECTED', 'EFFECTIVE', 'ACTIVE', 'FINISHED', 'TERMINATED') NOT NULL DEFAULT 'ACTIVE';

UPDATE `Contract`
SET `status` = 'ACTIVE'
WHERE `status` IN ('DRAFT', 'APPROVING', 'APPROVED', 'EFFECTIVE');

UPDATE `Contract`
SET `status` = 'TERMINATED'
WHERE `status` IN ('REJECTED', 'FINISHED');

ALTER TABLE `Contract`
  MODIFY COLUMN `status` ENUM('ACTIVE', 'TERMINATED') NOT NULL DEFAULT 'ACTIVE';

DROP TABLE IF EXISTS `contract_approval_workflows`;
